easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Movie
        - App\Entity\Room
        - App\Entity\User
        - App\Entity\Screening
        - App\Entity\Reservation